### ISSUE TITLE
Drag and drop between two Blazor data grids

### ISSUE THREAD

**Issue by mwpowellhtx** [DevExpress-Examples/datagrid-how-to-reorder-rows-using-drag-and-drop-t152596#1]
Hello, I'd like to extend this idea if possible, how to drag and drop items between like-item data grids, if possible. Is it possible? I'll experiment, but if y'all happened to know, would be helpful as well. Thanks!

**Comment by artem-kurchenko** [comment]
Hi,

This example covers only DevExtreme DataGrid. To get assistance regarding Blazor DataGrid, please contact us in the [Support Center](https://supportcenter.devexpress.com/ticket/create) We'll be happy to help.
